### ISSUE TITLE
Sudo-Auto Bunnyhop

### ISSUE THREAD

**Issue by BlindTwig** [Concussion-Studios/tfcs-source#18]
**Describe the bug**
This is a tough one to explain. Basically, if you press and hold jump while in mid-air, you'll jump again the moment you land. It requires you to do it again each jump, hence the name "sudo-auto bunnyhop.

**To Reproduce**
1. Jump in the air (Easier to do from high up since there's more time, but can be at any height)
2. Press and hold jump while in the air
3. Land, and it'll cause you to jump again instantly.

**Expected behavior**
You should just land without anything else happening.

**Additional context**
I'm unsure if this is really worth reporting. It's a simple bug that's somewhat helpful for bunnyhopping, and if we implement auto-bhopping ourselves this bug won't matter at all. Really depends on whether or not we do that, I guess.

I wanted to include a video, but it'd be pointless since you wouldn't see my keyboard.

**Comment by chrisfriend2** [comment]
This is intended behavior to test the feasibility of Quake 1 style jumping. To turn it off, do tfc_bhops 0. Additionally, tfc_max_bhop_speed can be used to alter max speed.
